CREATE TABLE Videos ( id INT NOT NULL AUTO_INCREMENT,name CHAR(255) NOT NULL, brand CHAR(255) NOT NULL, published DATE NOT NULL, PRIMARY KEY (id));

CREATE TABLE Views ( id INT NOT NULL AUTO_INCREMENT,videoid INT NOT NULL, viewdate DATE NOT NULL, PRIMARY KEY (id));
